mvm/items/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, BooleanField, IntegerField, MultipleFileField

from wtforms.validators import DataRequired, Length, NumberRange
from flask_babel import lazy_gettext

class CreateItemForm(FlaskForm):
    item_file = FileField(lazy_gettext('Item file'), validators=[DataRequired(),FileAllowed(['jpg', 'jpeg', 'png'])])
    itemname = StringField(lazy_gettext('Name for item'), validators=[DataRequired(), Length(min=1, max=35)]) 
    analysis_keywords = BooleanField(lazy_gettext('analysis of keywords'))
    analysis_persons = BooleanField(lazy_gettext('analysis of persons'))
    analysis_celebs = BooleanField(lazy_gettext('analysis of celebs'))
    analysis_targets = BooleanField(lazy_gettext('analysis of targets'))
    analysis_text = BooleanField(lazy_gettext('analysis of text'))
    analysis_labels = BooleanField(lazy_gettext('analysis of labels'))
    analysis_threshold = IntegerField(lazy_gettext('threshold for analysis'), validators=[DataRequired(), NumberRange(min=0, max=100)])
    submit = SubmitField(lazy_gettext('OK'))
    
class MultipleItemForm(FlaskForm):
    item_files = MultipleFileField(lazy_gettext('Item files'), validators=[FileAllowed(['jpg', 'png'])])
    itemname = StringField(lazy_gettext('Name for item'), validators=[DataRequired(), Length(min=1, max=35)]) 
    analysis_keywords = BooleanField(lazy_gettext('analysis of keywords'))
    analysis_persons = BooleanField(lazy_gettext('analysis of persons'))
    analysis_celebs = BooleanField(lazy_gettext('analysis of celebs'))
    analysis_targets = BooleanField(lazy_gettext('analysis of targets'))
    analysis_text = BooleanField(lazy_gettext('analysis of text'))
    analysis_labels = BooleanField(lazy_gettext('analysis of labels'))
    analysis_threshold = IntegerField(lazy_gettext('threshold for analysis'), validators=[DataRequired(), NumberRange(min=0, max=100)])
    submit = SubmitField(lazy_gettext('OK'))   

mvm/main/routes.py
from flask import Blueprint
from flask import render_template, request
from mvm import db
from mvm.models import Item, Keyword, ItemKeyword, Person
from mvm.analytics.forms import SearchItemForm

main = Blueprint('main', __name__)

def create_texts(item):
    foundkeywords = False
    foundtargets = False
    foundcelebrities = False
    foundtext = False
    foundlabel = False
    line1 = ""
    line4 = ""
    characterLine = 23
    keywords = Keyword.query.join(ItemKeyword).filter_by(itemin=item)
    for keyword in keywords:
        if len(line1) == 0:
            foundkeywords = True        
            line1=keyword.keywordtextname
        else:
            line1=line1 + ", " + keyword.keywordtextname  
        if keyword.label:
            if len(line4) == 0:
                foundlabel = True        
                line4=keyword.keywordtextname
            else:
                line4=line4 + ", " + keyword.keywordtextname              
    line2 = ""
    for person in Person.query.filter_by(itemin=item):
        if person.relatedcelebrity:
            text=person.relatedcelebrity.name
            foundcelebrities=True
        elif  person.foundtargetimage:   
            text=person.foundtargetimage.imagefortarget.name
            foundtargets=True
        else:
            continue
        if len(line2) == 0:
            line2=text
        else:
            line2=line2 + ", " + text 
    line3=""
    text =  item.text       
    if len(text)>0:
        line3 = str(item.text)
        foundtext = True
    
    if len(line1)>characterLine:
        line1=line1[0:characterLine-3] + "..."
    if len(line2)>characterLine:
        line2=line2[0:characterLine-3] + "..."
    if len(line3)>characterLine:
        line3=line3[0:characterLine-3] + "..."   
    if len(line4)>characterLine*3:
        line4=line4[0:characterLine*3-3] + "..." 
    entry = {}
    entry["line1"]=line1
    entry["line2"]=line2
    entry["line3"]=line3
    entry["line4"]=line4
    entry["foundkeywords"] = foundkeywords
    entry["foundtargets"] = foundtargets
    entry["foundcelebrities"] = foundcelebrities
    entry["foundtext"] = foundtext
    entry["foundlabel"] = foundlabel
    return line1, line2, line3,  line4, foundkeywords, foundtargets, foundcelebrities, foundtext, foundlabel, entry

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    items = Item.query.order_by(Item.date_posted.desc()).paginate(page=page, per_page=12)
    texts={}  
    for item in items.items:
        line1, line2, line3, line4, foundkeywords, foundtargets, foundcelebrities, foundtext, foundlabel, entry = create_texts(item)
        texts[item.id]=entry 
    itemsall = Item.query.order_by(Item.date_posted.desc()).all()
    searchform = SearchItemForm()
    return render_template('home.html', items=items, itemsall=itemsall, searchform=searchform, texts=texts)


@main.route("/about")
def about():
    db.drop_all()
    db.create_all()
    itemsall = Item.query.order_by(Item.date_posted.desc()).all()
    searchform = SearchItemForm()
    return render_template('about.html', title='About', itemsall=itemsall, searchform=searchform)

mvm/users/routes.py
from flask import Blueprint, current_app
from flask import render_template, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from mvm import db, bcrypt
from mvm.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from mvm.models import User, Item
from mvm.users.utils import save_picture, send_reset_email
from flask_babel import gettext
from mvm.analytics.forms import SearchItemForm



users = Blueprint('users', __name__)



@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashedpassword = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashedpassword)
        db.session.add(user)
        db.session.commit()
        current_app.logger.info('New user registered {} {}'.format(user.username, user.email))  
        flash(gettext('Your account has been created! you are able to log in'), 'success')
        return redirect(url_for('users.login'))
    itemsall = Item.query.order_by(Item.date_posted.desc()).all()
    searchform = SearchItemForm()    
    return render_template('register.html', title='Register', form=form, itemsall=itemsall, searchform=searchform)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:     
            current_app.logger.warning('Unsuccessful login attempt {}'.format(form.email.data))  
            flash(gettext('Login Unsuccessful. Please check email and password'), 'danger')
    itemsall = Item.query.order_by(Item.date_posted.desc()).all()
    searchform = SearchItemForm()    
    return render_template('login.html', title='Login', form=form, itemsall=itemsall, searchform=searchform)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))



@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
           picturefile = save_picture(form.picture.data) 
           current_user.image_file = picturefile
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash(gettext('Your account has been updated!'), 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    imagefile = url_for('static', filename='images/profile_pics/' + current_user.image_file)
    itemsall = Item.query.order_by(Item.date_posted.desc()).all()
    searchform = SearchItemForm()    
    return render_template('account.html', title='Account', imagefile=imagefile, form=form, itemsall=itemsall, searchform=searchform)

    

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RequestResetForm()
    if form.validate_on_submit():
       user = User.query.filter_by(email=form.email.data).first()
       send_reset_email(user)
       flash(gettext('An email has been sent with instructions to reset your password.'), 'info')
       return redirect(url_for('users.login'))
    itemsall = Item.query.order_by(Item.date_posted.desc()).all()
    searchform = SearchItemForm()    
    return render_template('reset_request.html', title='Reset Password', form=form, itemsall=itemsall, searchform=searchform)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash(gettext('That is an invalid or expired token'), "warning")
        return redirect(url_for('users.reset_request'))
    form=ResetPasswordForm()
    if form.validate_on_submit():
        hashedpassword = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashedpassword
        db.session.commit()
        flash(f'Your password has been updated! you are able to log in', 'success')
        return redirect(url_for('users.login'))
    itemsall = Item.query.order_by(Item.date_posted.desc()).all()
    searchform = SearchItemForm()
    return render_template('reset_token.html', title='Reset Password', form=form, itemsall=itemsall, searchform=searchform)

mvm/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ imagefile }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ _('Account Info') }}</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
    
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>                        
                        {% endfor %}
                    {% endif %}
                </div>    
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
        <legend class="border-bottom mb-4">{{ _('Targets') }}</legend>       
        <div class="row justify-content-center">  
            {% if current_user.targets | count > 0 %}
                    {% for target in current_user.targets %}           
                                <a href="{{ url_for('analytics.target', target_id=target.id) }}">
                                <div class="card border-0 mb-0 mr-2" style="width: 10rem;"> 
                                    {% if target.targetimages | count > 0 %} 
                                        <img class="card-img-top" src="{{ url_for('static', filename='images/thumbnails/' + target.targetimages[0].thumbnail) }}">
                                    {% else %}                                                
                                        <img class="card-img-top" src="{{ url_for('static', filename='images/thumbnails/labelthumbnail.jpg') }}">
                                        <div class="card-img-overlay px-2">
                                          <p class="card-subtitle mb-0 text-danger"><small>{{ _('No images defined!') }}</small></p>
                                        </div>

                                    {% endif%}
                                    <div class="card-body px-0 pt-1">
                                            <h6 class="card-title mb-0">{{ target.name}}</h6>
                                            <p class="card-subtitle mb-0 text-muted"><small>{{ target.date_created.strftime('%d-%m-%y') }} {{ target.targetimages | count }} {{ _('image(s)') }}</small></p>                    
                                    </div>
                                </div>
                                </a>
                    {% endfor %}           
            {% else %}    
                    <p class='text-muted'>{{ _('No targets defined') }}      
            {% endif%}  
        </div>			



            <a class="btn btn-secondary btn-sm mt-1 mb-1"  href="{{ url_for('analytics.new_target', user_id=current_user.id) }}">{{ _('New') }}</a>   
    </div>
{% endblock content %}

mvm/templates/attributes.html
{% extends "layout.html" %}
{% block content %}
     <ul class="list-group">
        {% for attribute in attributes.items %}     
            <a class="list-group-item list-group-item-light"  href="{{ url_for('analytics.attribute_items', attributetextname=attribute.attributetextname) }}">{{ attribute.attributetextname }}  (  {{ _('Found for') }} {{ attribute.countpersons }} {{ _('persons') }} )</a>           
        {% endfor %} 
    </ul>
    {% for page_num in attributes.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if attributes.page == page_num %}      
                <a class="btn btn-info mb-4" href="{{ url_for('analytics.attributes', page=page_num)}}">{{ page_num }}</a>              
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('analytics.attributes', page=page_num)}}">{{ page_num }}</a>
            {% endif %}
        {% else %}
        ...
        {% endif %}
    {% endfor %}        
{% endblock content %}

mvm/templates/celebrities.html
{% extends "layout.html" %}
{% block content %}
     <ul class="list-group">
        {% for celebrity in celebrities.items %}                 
             <a class="list-group-item list-group-item-light"  href="{{ url_for('analytics.celebrity_items', aws_id=celebrity.aws_id) }}">{{ celebrity.name }}  (  {{ _('Found for') }} {{ celebrity.countpersons }} {{ _('persons') }} )</a>
        {% endfor %} 
    </ul>
    {% for page_num in celebrities.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if celebrities.page == page_num %}      
                <a class="btn btn-info mb-4" href="{{ url_for('analytics.celebrities', page=page_num)}}">{{ page_num }}</a>              
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('analytics.celebrities', page=page_num)}}">{{ page_num }}</a>
            {% endif %}
        {% else %}
        ...
        {% endif %}
    {% endfor %}        
{% endblock content %}

mvm/templates/celebrity_items.html
{% extends "layout.html" %}
{% block content %}
<h1 class="mb-3">Items for {{ celebrity.name }} ({{ items.total }})</h1>
    <div class="card-deck">   
    {% for item in items.items %}

                <a href="{{ url_for('items.item', item_id=item.id) }}">
                <div class="card border-0 mb-0" style="width: 10rem;">                                

                  {% if texts[item.id]["foundlabel"] %}
                      <img class="card-img-top" src="{{ url_for('static', filename='images/thumbnails/labelthumbnail.jpg') }}">
                      <div class="card-img-overlay px-2">
                          <p class="card-subtitle mb-0 text-danger"><img class="card-img-top" style="width:15px;height:15px;"  src="{{ url_for('static', filename='images/icons/Label.jpg') }}"><small>{{ texts[item.id]["line4"] }}</small></p>
                      </div>
                  {% else %}
                    <img class="card-img-top" src="{{ url_for('static', filename='images/thumbnails/' + item.thumbnail) }}">
                  {% endif %}
                  <div class="card-body px-0 pt-1">
                    <h6 class="card-title mb-0">{{ item.itemname}}</h6>
                    <p class="card-subtitle mb-0 text-muted"><small>{{ item.owner.username}} {{ item.date_posted.strftime('%d-%m-%y') }}</small></p>                    
                        {% if texts[item.id]["foundkeywords"] %}
                            <p class="card-subtitle mb-0"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/Keyword.jpg') }}"><small>{{ texts[item.id]["line1"] }}</small></p>
                        {%endif%}
                        {% if texts[item.id]["foundcelebrities"] and texts[item.id]["foundtargets"] %}
                            <p class="card-subtitle mb-0"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/Target.jpg') }}"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/VIP.jpg') }}"><small>{{ texts[item.id]["line2"] }}</small></p>
                        {% elif texts[item.id]["foundcelebrities"] %}    
                            <p class="card-subtitle mb-0"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/VIP.jpg') }}"><small>{{ texts[item.id]["line2"] }}</small></p>
                        {% elif texts[item.id]["foundtargets"] %}    
                            <p class="card-subtitle mb-0"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/Target.jpg') }}"><small>{{ texts[item.id]["line2"] }}</small></p>
                        {%endif%}
                        {% if texts[item.id]["foundtext"] %}
                            <p class="card-subtitle mb-0"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/Text.jpg') }}"><small>{{ texts[item.id]["line3"] }}</small></p>
                        {%endif%}
                  </div>
                </div>
                </a>
    {% endfor %}
   </div>
    {% for page_num in items.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}      
            {% if items.page == page_num %}      
                <a class="btn btn-info mb-4" href="{{ url_for('analytics.celebrity_items', aws_id=celebrity.aws_id, page=page_num)}}">{{ page_num }}</a>              
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('analytics.celebrity_items', aws_id=celebrity.aws_id, page=page_num)}}">{{ page_num }}</a>
            {% endif %}
        {% else %}
        ...
        {% endif %}
    {% endfor %}        
{% endblock content %}

mvm/templates/create_target.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">           
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    <legend class="border-bottom mb-4">{{ _('Images for target') }}</legend> 
    <div class="row justify-content-center"> 
        {% if target is defined %}
            {% if target.targetimages is defined %}
                {% if target.targetimages | count > 0 %}
                     {% for targetimage in target.targetimages %}
                         <a href="{{ url_for('analytics.targetimage', targetimage_id=targetimage.id) }}">
                         <div class="card border-0 mb-0 mr-2" style="width: 10rem;"> 
                             <img class="card-img-top" src="{{ url_for('static', filename='images/thumbnails/' + targetimage.thumbnail) }}">
                             <div class="card-body px-0 pt-1">
                                 <h6 class="card-title mb-0">{{ targetimage.name }}</h6>
                                 <p class="card-subtitle mb-0 text-muted"><small>{{ target.date_created.strftime('%d-%m-%y') }} {{ target.targetimages | count }} {{ _('image(s)') }}</small></p>                    
                             </div>
                         </div>   
                    {% endfor %}
                {% else %}    
                    <p class='text-muted'>{{ _('No images for this target defined') }}              
                {% endif %} 
            {% endif %} 
              
        {% endif %} 
    </div>   
    <a class="btn btn-secondary btn-sm mt-1 mb-1"  href="{{ url_for('analytics.new_targetimage', target_id=target.id) }}">{{ _('New') }}</a>  
</div>
{% endblock content %}

mvm/templates/home.html
{% extends "layout.html" %}
{% block content %}     
    <div class="row justify-content-center">   
    {% for item in items.items %}

                <a href="{{ url_for('items.item', item_id=item.id) }}">
                <div class="card border-0 mb-0 mr-2" style="width: 10rem;">                                

                  {% if texts[item.id]["foundlabel"] %}
                      <img class="card-img-top" src="{{ url_for('static', filename='images/thumbnails/labelthumbnail.jpg') }}">
                      <div class="card-img-overlay px-2">
                          <p class="card-subtitle mb-0 text-danger"><img class="card-img-top" style="width:15px;height:15px;"  src="{{ url_for('static', filename='images/icons/Label.jpg') }}"><small>{{ texts[item.id]["line4"] }}</small></p>
                      </div>
                  {% else %}
                    <img class="card-img-top" src="{{ url_for('static', filename='images/thumbnails/' + item.thumbnail) }}">
                  {% endif %}
                  <div class="card-body px-0 pt-1">
                    <h6 class="card-title mb-0">{{ item.itemname}}</h6>
                    <p class="card-subtitle mb-0 text-muted"><small>{{ item.owner.username}} {{ item.date_posted.strftime('%d-%m-%y') }}</small></p>                    
                        {% if texts[item.id]["foundkeywords"] %}
                            <p class="card-subtitle mb-0"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/Keyword.jpg') }}"><small>{{ texts[item.id]["line1"] }}</small></p>
                        {%endif%}
                        {% if texts[item.id]["foundcelebrities"] and texts[item.id]["foundtargets"] %}
                            <p class="card-subtitle mb-0"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/Target.jpg') }}"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/VIP.jpg') }}"><small>{{ texts[item.id]["line2"] }}</small></p>
                        {% elif texts[item.id]["foundcelebrities"] %}    
                            <p class="card-subtitle mb-0"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/VIP.jpg') }}"><small>{{ texts[item.id]["line2"] }}</small></p>
                        {% elif texts[item.id]["foundtargets"] %}    
                            <p class="card-subtitle mb-0"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/Target.jpg') }}"><small>{{ texts[item.id]["line2"] }}</small></p>
                        {%endif%}
                        {% if texts[item.id]["foundtext"] %}
                            <p class="card-subtitle mb-0"><img class="card-img-top" style="width:8px;height:8px;"  src="{{ url_for('static', filename='images/icons/Text.jpg') }}"><small>{{ texts[item.id]["line3"] }}</small></p>
                        {%endif%}
                  </div>
                </div>
                </a>
    {% endfor %}
   </div>
    {% for page_num in items.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if items.page == page_num %}      
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num)}}">{{ page_num }}</a>              
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num)}}">{{ page_num }}</a>
            {% endif %}
        {% else %}
        ...
        {% endif %}
    {% endfor %}        
{% endblock content %}

mvm/templates/keywords.html
{% extends "layout.html" %}
{% block content %}
     <ul class="list-group">
        {% for keyword in keywords.items %}     
            <a class="list-group-item list-group-item-light" href="{{ url_for('analytics.keyword_items', keywordtextname=keyword.keywordtextname) }}">{{ keyword.keywordtextname }} ( {{ keyword.countitems }} )</a>           
        {% endfor %} 
    </ul>
    {% for page_num in keywords.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if keywords.page == page_num %}      
                <a class="btn btn-info mb-4" href="{{ url_for('analytics.keywords', page=page_num)}}">{{ page_num }}</a>              
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('analytics.keywords', page=page_num)}}">{{ page_num }}</a>
            {% endif %}
        {% else %}
        ...
        {% endif %}
    {% endfor %}        
{% endblock content %}

mvm/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ _('Log In') }}</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">{{ _('Forgot Password?') }}</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            {{ _('Need An Account?') }} <a class="ml-2" href="{{ url_for('users.register') }}">{{ _('Sign Up Now') }}</a>
        </small>
    </div>
{% endblock content %}